COLUMNS:       
  Geography: object        
  Gender: object 
  NumOfProducts: int64 
  IsActiveMember: int64 
  sufficient_balance: int64 
  is_CreditScore_low: int64 
  CreditScore: int64  
  Age: float64
  Tenure: int64  
  Balance: float64 
  EstimatedSalary: float64
    
TARGET_COLUMN: 
  name: Exited             



